//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int ID { get; set; }
        public string Location1 { get; set; }
        public Nullable<int> Location_INC_ID { get; set; }
    
        public virtual Location Locations1 { get; set; }
        public virtual Location Location2 { get; set; }
    }
}
